apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeabtsega
  annotations:
    submitted-by: "yeabtsega-yifat-ugr9766"
  labels:
    app: yeabtsega
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeabtsega
      tier: frontend
  template:
    metadata:
      labels:
        app: yeabtsega
        tier: frontend
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: devopsjourney1/yeabtsega
          ports:
            - containerPort: 80
